Fixed a potential bug with classloaders. On the server side, Cactus looks for the TestCase class by searching first the WebApp Classloader and then the Context ClassLoader. However, the Context ClassLoader is only searched if an Exception (subclass of <code>Exception</code>) is raised. Thus, if a <code>NoClassDefFoundError</code> had been raised, Cactus would not have searched in the Context ClassLoader.
git-svn-id: http://svn.apache.org/repos/asf/jakarta/cactus/trunk@236851 13f79535-47bb-0310-9956-ffa450edef68