Update maven-checkstyle-plugin
Otherwise we had the following errors during the build:
[ERROR] Failed to execute goal
org.apache.maven.plugins:maven-checkstyle-plugin:2.4:checkstyle
(checkstyle) on project cactus.core.framework.javaEE.12-13-14: Execution
checkstyle of goal
org.apache.maven.plugins:maven-checkstyle-plugin:2.4:checkstyle failed.
NullPointerException -> [Help 1]

Due to resource resolving Issues:
[DEBUG] URLResourceLoader: Exception when looking for
'build-tools/checkstyle.license
java.net.MalformedURLException: no protocol:
build-tools/checkstyle.license

2.6 was the first working version.