Remove install-maven-one-repository goal from maven1 plugin
Maven1 is not fully supported anymore (see the following error), this
fix is just to get the build running.
In the future the plugin may be dropped copletely.

[ERROR] Failed to execute goal
org.apache.maven.plugins:maven-one-plugin:1.3:install-maven-one-repository
(default) on project cactus.maven1.plugin: Execution default of goal
org.apache.maven.plugins:maven-one-plugin:1.3:install-maven-one-repository
failed: Unable to load the mojo 'install-maven-one-repository' (or one
of its required components) from the plugin
'org.apache.maven.plugins:maven-one-plugin:1.3':
com.google.inject.ProvisionException: Unable to provision, see the
following errors: